version: '3.9'

services:
  mongo:
    image: mongo:4.4.2
    ports:
      - "27017:27017"
    networks:
      - app-network

  user-service:
    build: ./user-service
    ports:
      - "3001:3001"
    networks:
      - app-network
    depends_on:
      - mongo

  product-service:
    build: ./product-service
    ports:
      - "3002:3002"
    networks:
      - app-network
    depends_on:
      - mongo

  order-service:
    build: ./order-service
    ports:
      - "3003:3003"
    networks:
      - app-network
    depends_on:
      - mongo

networks:
  app-network:
    driver: bridge